const express = require("express");
const songsAdBreak = require("../services/songsadbreak");
const router = express.Router();
const { authenticate, authorize } = require("../middleware/authorization");

// 1. Users add the ad break text.
router.post("/submitAdText", express.json(), authenticate, authenticate, authorize("admin", "user"), async (req, res) => {
  const { username, adBreakText } = req.body;

  if (!adBreakText) {
    return res.status(400).json({
      message: "Please insert the ad break text.",
    });
  }

  // we can defferneciate two cases
  // 1. admin text will be autogenerated
  // 2. user text will go to the pending list for admin approval
  if (req.user.role === "admin") {
    let dbResult = await songsAdBreak.addAdBreak(
      username,
      adBreakText,
      "approved",
    );
    let adBreakId = dbResult;
    adBreakId = dbResult.lastInsertRowid;
    console.log(`Start the audio generation of the ad break ${adBreakId}...`);
    await songsAdBreak.generateAudio(adBreakId);
  } else if (req.user.role === "user") {
    songsAdBreak.addAdBreak(username, adBreakText, "pending");
    // THis part is just for sending the admin
    // a notifciation via Socket to reload his page
    // and see the new pending ad break
    const io = req.app.get("io");
    io.emit("newAdBreak");
  } else {
    return res.status(401).json({
      message: "The current role is nor provided",
    });
  }
  res.status(200).json({ message: "Ad break submitted successfully!" });
});

// 2. Display pending ad break texts at the admin dashboard.
router.get("/pending", authenticate, (req, res) => {
  const pendingAdBreaks = songsAdBreak.getPendingAdBreaks();
  res.json(pendingAdBreaks);
});

// 3. Admin approves the ad break text.
router.post("/:id/approveAdText", authenticate, async (req, res) => {
  const adBreakId = parseInt(req.params.id);

  if (!adBreakId) {
    return res.status(400).json({ message: "Invalid user ID" });
  }

  try {
    songsAdBreak.approveAdBreak(adBreakId);
    console.log(`Start the audio generation of the ad break ${adBreakId}...`);
    await songsAdBreak.generateAudio(adBreakId);
    return res
      .status(200)
      .json({ message: "Ad break text has been approved." });
  } catch (error) {
    return res.status(500).json({ message: "Failed to approve ad break." });
  }
});

// 4. Admin denies the ad break text.
router.post("/:id/rejectAdText", authenticate, (req, res) => {
  const adBreakId = parseInt(req.params.id);

  if (!adBreakId) {
    return res.status(400).json({ message: "Invalid ad break ID" });
  }

  try {
    songsAdBreak.rejectAdBreak(adBreakId);
    return res.status(200).json({ message: "Ad break text has been denied." });
  } catch (error) {
    return res.status(500).json({ message: "Failed to reject ad break." });
  }
});

//------------------------------------------------//
//fira new update.
//5. Convert the ad break text to audio and save the audio to database.
router.get("/generateAudio", async (req, res) => {
  const { adBreakId } = req.query;
  await songsAdBreak.generateAudio(adBreakId);
  res.status(200).json({
    message: " Ad break audio is successfully generated.",
  });
});

module.exports = router;
